### ISSUE TITLE
AVPlayer audio disables audio from VoxImplant call

### ISSUE THREAD

**Issue by ynewdev** [voximplant/iosVoxImplantDemoNewAPI#4]
VioxImolant audio is disabled when I execute play function on AVPlayer.

I think the problem similar as in https://github.com/twilio/video-quickstart-objc/issues/62

**Comment by Hastewave** [comment]
The problem still exist, need help!

**Comment by niveuseverto** [comment]
Greetings.

This task is on our to-do list and we will check it as soon as we have some spare hands.

Please note that system-level audio mixing is not always controlled by individual apps. For example, if you start a YouTube video and then a video player, the audio from video player will play and audio from YouTube will not. This is how operating system handle things, and YouTube can't do anything about it.

**Comment by 3Bepo6ou** [comment]
Dear Vixomplant Team!
Actually we were going to user your platform in a commercial way but also met this nasty issue.
We are expecting a lot of traffic from our innovative product.
It really blocks our needs and we would need to use another solution / product because of it.
We like your API and price policy.
Can you fix this issue ASAP? Otherwise as a Project Manager i will have to refuse of Voximplant :(
Please prioritise this issue in your backlog!

**Comment by grigoryvp** [comment]
Do you have an example of another solution that successfully fix such kind of problem, so we can investigate it better?

**Comment by 3Bepo6ou** [comment]
Unfortunately, no.
But why are you asking me?!
Your colleague wrote 15 days ago that this issue is in your to-do list.
Can i take an interest and ask you the priority of this issue in your product backlog?

**Comment by grigoryvp** [comment]
The research of this issue is on our to-do list. But what we know so far is that it's an OS feature that is not controlled by appliation. Youtube is an example, the audio will stop if you execute function on AVPlayer. So if you have this another solution that actually CAN do such things we can learn what they do and how they do it.

**Comment by advignweb** [comment]
The main problem is that we cannot continue voximplant audio session after the end of execution of an audio file.

**Comment by Hastewave** [comment]
The main problem is that we cannot continue voximplant audio session after the end of execution of an audio file.

**Comment by niveuseverto** [comment]
Greetings.

The research of this issue is currently in progress and we plan to resolve it in the next Voximplant iOS SDK release.

**Comment by niveuseverto** [comment]
Greetings.

This issue is resolved in 2.13.0.

Please, update and check if everything is working now.
